
network: 'irc.freenode.net'
port: 6667
nick: 'gordn'
name: 'Gordon the Turtle'
logs: '/logs'
timezone: 'US/Pacific'
smtp_server: '127.0.0.1'
password: 'somepassword!'

standups:
    core:
        dev_channel: '#docker-dev'
        standup_channel: '#docker-meeting'
        warmup_duration: 60
        logfile_name: 'standup'
        send_logs_from:  'standup-list@acme.com'
        vote_duration: 60
        speak_limit: 3
        send_logs_from:  'keeb@awesome.com'
        send_logs_to:
            - 'keeb@acme.com'

